# Generated by Django 2.1.1 on 2018-10-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='estado_civil',
            field=models.IntegerField(choices=[(1, 'Solteiro'), (2, 'Casado'), (3, 'Separado'), (4, 'Divorciado'), (5, 'Viúvo')]),
        ),
    ]
