# Generated by Django 2.1.1 on 2018-09-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('apelido', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(max_length=20)),
            ],
        ),
    ]
